defaults:
  - calibration@calibration_cfg: default
  - _self_

_target_: src.models.baseline_classification_lit_module.BaselineClassificationLitModule

name: timm_mc_baseline
# backbone
net:
  _target_: src.models.baseline.baseline_models.BaselineClassifier
  arch: resnet18
  num_classes: 8
  dropout_p: 0.2
  pretrained: true

class_weights: null

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

# scheduler:
#   _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#   _partial_: true
#   mode: min
#   factor: 0.1
#   patience: 10

scheduler:
    _target_: torch.optim.lr_scheduler.MultiStepLR
    _partial_: true
    milestones: [30, 70, 100]
    gamma: 0.1

# --- Training setup ---
compile: false # compile model for faster training with pytorch 2.0
num_classes: 8
hist_bins: 25 # no of bins for drawing histogram at the end of training on testset
test_name: "test_predictions.csv" # test csv name
csv_save_path: "csv/" # path to save csv files
log_csv: false
log_test_metrics: true
class_freq: null
use_mc: false # mc for testing/inference (double check)
mc_passes: 10

# Calibration loss weights/config: see configs/model/calibration/default.yaml
log_calibration_terms: true
compute_calibration_on_val: true