_target_: src.models.timm_classification_lit_module.TimmClassificationLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.timm_classification_models.TimmSNGPClassifier
  model_name: resnet50
  num_classes: 8
  pretrained: True
  in_chans: 3
  reduction_dim: 512
  use_spec_norm: True # required for TimmSNGPClassifier
  spec_norm_bound: 0.95 # required for TimmSNGPClassifier
  spec_norm_iteration: 1 # required for TimmSNGPClassifier
  covariance_likelihood: "gaussian" # kwarg for SNGP
  covariance_momentum: 0.999 # kwarg for SNGP
  normalize_input: True # kwarg for SNGP
  output_bias_trainable: False # kwarg for SNGP
  random_features: 1024 # kwarg for SNGP
  scale_random_features: False # kwarg for SNGP <-- change to False to mirror Edward2
  trainable_kernel_scale: True # kwarg for SNGP

# compile model for faster training with pytorch 2.0
compile: false

#no of bins for drawing histogram at the end of training on testset
hist_bins: 25

#test csv name
test_name: "test_predictions.csv"
log_csv: false

use_mean_field_logits: false