#!/usr/bin/env python3
"""Export a v2 checkpoint to a self-contained HuggingFace `trust_remote_code` bundle.

Supersedes `src/hf_model.py`, `src/hf_sngp_model.py`, `src/_hf_sngp_model.py`,
`hf_checkpoint/hf_model.py` (four hand-maintained copies of backbone/SNGP
construction code) and `scripts/migrate_to_hf.py` (baseline-only, and required
re-typing `arch`/`num_classes`/... on the CLI even though the checkpoint already
knows them).

The generated `modeling_<family>.py` has zero `src.*` imports: it's assembled by
concatenating the *source* of the canonical, dependency-light net modules
(`src/models/backbones.py`, `src/models/outputs.py`,
`src/models/components/spectral_norm.py`, and the net class itself) with a thin
`transformers.PreTrainedModel` wrapper template. Edit those files, not the generated
one -- re-run this script to regenerate it. Architecture identity comes straight from
the checkpoint's `net_spec` (see `src/checkpointing/`), so there is nothing to retype.

Usage:
    uv run scripts/hf/export_to_hub.py --ckpt path/to/model.ckpt --out hf_export/my-model
    uv run scripts/hf/export_to_hub.py --ckpt path/to/model.ckpt --out hf_export/my-model \
        --push-to-hub org/my-model --hf-token $HF_TOKEN
"""
import argparse
import inspect
import json
import re
from pathlib import Path
from typing import Optional

import rootutils
import torch

rootutils.setup_root(__file__, indicator=".project-root", pythonpath=True)

from src.checkpointing.io import read_meta  # noqa: E402
from src.models import backbones as backbones_module  # noqa: E402
from src.models import outputs as outputs_module  # noqa: E402
from src.models.baseline.baseline_models import BaselineClassifier  # noqa: E402
from src.models.components import spectral_norm as spectral_norm_module  # noqa: E402
from src.models.sngp.sngp_classifier import RandomFeatureGaussianProcess, SNGPClassifier  # noqa: E402

_REGISTER_NET_DECORATOR = re.compile(r"^@register_net\([^)]*\)\n", re.MULTILINE)
_SPECTRAL_NORM_IMPORT_LINE = "from src.models.backbones import SPECTRAL_NORM_COMPATIBLE\n"


def _class_source(obj) -> str:
    """`inspect.getsource()`, with any `@register_net(...)` decorator stripped -- the
    exported bundle doesn't vendor the registry, and doesn't need to: the HF wrapper
    below reads architecture identity from `PretrainedConfig`, not `net.spec`."""
    return _REGISTER_NET_DECORATOR.sub("", inspect.getsource(obj))


def _build_baseline_module_source() -> str:
    header = (
        '"""Self-contained HF model code for a baseline classifier.\n\n'
        "Generated by scripts/hf/export_to_hub.py from src/models/backbones.py, "
        "src/models/outputs.py, and src/models/baseline/baseline_models.py -- edit "
        "those files, not this one; re-run the export script to regenerate it.\n\"\"\"\n"
        "from typing import Literal\n\n"
        "import torch\n"
        "import torch.nn.functional as F\n"
        "from transformers import PreTrainedModel, PretrainedConfig\n\n"
        'Backbone = Literal["resnet18", "resnet34", "resnet50", "vit_b_16", "vit_b_32", "vit_l_16", "vit_l_32", "vit_h_14"]\n'
    )
    return "\n\n".join([
        header.rstrip("\n"),
        inspect.getsource(backbones_module),
        inspect.getsource(outputs_module),
        _class_source(BaselineClassifier),
    ])


def _build_sngp_module_source() -> str:
    header = (
        '"""Self-contained HF model code for an SNGP classifier.\n\n'
        "Generated by scripts/hf/export_to_hub.py from src/models/backbones.py, "
        "src/models/outputs.py, src/models/components/spectral_norm.py, and "
        "src/models/sngp/sngp_classifier.py -- edit those files, not this one; "
        "re-run the export script to regenerate it.\n\"\"\"\n"
        "import math\n\n"
        "import torch\n"
        "from transformers import PreTrainedModel, PretrainedConfig\n\n"
    )
    spectral_norm_source = inspect.getsource(spectral_norm_module).replace(_SPECTRAL_NORM_IMPORT_LINE, "")
    return "\n\n".join([
        header.rstrip("\n"),
        inspect.getsource(backbones_module),
        inspect.getsource(outputs_module),
        spectral_norm_source,
        _class_source(RandomFeatureGaussianProcess),
        _class_source(SNGPClassifier),
    ])


_WRAPPER_TEMPLATE = '''

class {config_cls}(PretrainedConfig):
    model_type = "{model_type}"

    def __init__(self, net_spec=None, **kwargs):
        super().__init__(**kwargs)
        self.net_spec = net_spec or {{}}


class {wrapper_cls}(PreTrainedModel):
    """Load with:
        from transformers import AutoModel
        model = AutoModel.from_pretrained("<repo>", trust_remote_code=True)
    """
    config_class = {config_cls}
    base_model_prefix = "net"

    def __init__(self, config: {config_cls}):
        super().__init__(config)
        spec = dict(config.net_spec)
        spec.pop("name", None)
        self.net = {net_cls}(**spec)

    def forward(self, pixel_values: torch.Tensor, return_dict: bool = True):
        output = self.net(pixel_values)
        if return_dict:
            result = {{"logits": output.logits}}
            if output.variance is not None:
                result["variance"] = output.variance
            return result
        return output.logits
{extra_methods}'''

# transformers' generic state-dict-key-fixup unconditionally rewrites any key ending
# in "weight_v" from legacy `torch.nn.utils.weight_norm` parametrization naming to the
# newer `parametrizations.weight.original1` -- it doesn't check which parametrization
# actually produced the key, so it misfires on legacy `torch.nn.utils.spectral_norm`'s
# (unrelated) `weight_v` buffer too, silently discarding real weights on load. Disable
# it for this wrapper; none of our modules use weight_norm or the LayerNorm
# beta/gamma legacy names that method also handles.
_SPECTRAL_NORM_KEY_FIX_OVERRIDE = '''
    @staticmethod
    def _fix_state_dict_key_on_load(key):
        return key, False
'''

_FAMILIES = {
    "baseline_classifier": {
        "builder": _build_baseline_module_source,
        "net_cls": "BaselineClassifier",
        "wrapper_cls": "BaselineClassifierForImageClassification",
        "config_cls": "BaselineClassifierConfig",
    },
    "sngp_classifier": {
        "builder": _build_sngp_module_source,
        "net_cls": "SNGPClassifier",
        "wrapper_cls": "SNGPForImageClassification",
        "config_cls": "SNGPConfig",
    },
}


def _model_card(family: str, net_spec: dict, num_classes: int) -> str:
    arch = net_spec.get("arch", "unknown")
    return f"""---
tags:
  - image-classification
  - {arch}
  - pytorch
  - {family.replace("_", "-")}
---

# {family} ({arch})

Exported by `scripts/hf/export_to_hub.py`. Self-contained (`trust_remote_code`) --
loading requires no dependency on this project's source tree.

## Model Details

- **Family**: {family}
- **Backbone**: {arch}
- **Classes**: {num_classes}

## Usage

```python
from transformers import AutoModel
import torch

model = AutoModel.from_pretrained("<repo-or-local-dir>", trust_remote_code=True)
model.eval()

x = torch.randn(1, 3, 224, 224)
with torch.no_grad():
    output = model(x)
logits = output["logits"]
```

## Training

Trained with PyTorch Lightning + Hydra. See the project repository for training code
and configs.
"""


def export(ckpt_path: str, out_dir: Path, push_to_hub: Optional[str] = None, hf_token: Optional[str] = None) -> None:
    meta = read_meta(ckpt_path)
    family = meta.net_spec.get("name")
    if family not in _FAMILIES:
        raise ValueError(
            f"HF export is only implemented for {sorted(_FAMILIES)}, got net_spec.name={family!r}. "
            "Deep Ensemble export is not yet supported."
        )
    spec = _FAMILIES[family]

    checkpoint = torch.load(str(ckpt_path), map_location="cpu", weights_only=False)
    # Keep the "net." prefix as-is: the wrapper class below also names its net
    # attribute `self.net`, so the saved keys line up with the wrapper's own
    # state_dict() without any prefix guessing on transformers' side.
    net_state_dict = {
        key: value for key, value in checkpoint["state_dict"].items() if key.startswith("net.")
    }

    out_dir.mkdir(parents=True, exist_ok=True)

    module_source = spec["builder"]() + _WRAPPER_TEMPLATE.format(
        config_cls=spec["config_cls"],
        wrapper_cls=spec["wrapper_cls"],
        net_cls=spec["net_cls"],
        model_type=family,
        extra_methods=_SPECTRAL_NORM_KEY_FIX_OVERRIDE if family == "sngp_classifier" else "",
    )
    (out_dir / f"modeling_{family}.py").write_text(module_source)

    net_spec = dict(meta.net_spec)
    net_spec.pop("name", None)
    config = {
        "architectures": [spec["wrapper_cls"]],
        "model_type": family,
        "auto_map": {
            "AutoConfig": f"modeling_{family}.{spec['config_cls']}",
            "AutoModel": f"modeling_{family}.{spec['wrapper_cls']}",
        },
        "net_spec": {**net_spec, "name": family},
        **net_spec,
    }
    (out_dir / "config.json").write_text(json.dumps(config, indent=2))

    try:
        from safetensors.torch import save_file
        save_file(net_state_dict, str(out_dir / "model.safetensors"))
        weights_filename = "model.safetensors"
    except ImportError:
        torch.save(net_state_dict, out_dir / "pytorch_model.bin")
        weights_filename = "pytorch_model.bin"

    (out_dir / "README.md").write_text(_model_card(family, net_spec, meta.num_classes))

    print(f"Exported {family} (num_classes={meta.num_classes}) to {out_dir}")
    print(f"  modeling_{family}.py, config.json, {weights_filename}")
    print("\nLoad locally with:")
    print("  from transformers import AutoModel")
    print(f"  model = AutoModel.from_pretrained('{out_dir}', trust_remote_code=True)")

    if push_to_hub:
        from huggingface_hub import upload_folder

        upload_folder(repo_id=push_to_hub, folder_path=str(out_dir), token=hf_token, repo_type="model")
        print(f"\nPushed to https://huggingface.co/{push_to_hub}")
        print(f"  model = AutoModel.from_pretrained('{push_to_hub}', trust_remote_code=True)")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--ckpt", required=True, help="Path to a v2 Lightning checkpoint")
    parser.add_argument("--out", required=True, type=Path, help="Output directory for the HF bundle")
    parser.add_argument("--push-to-hub", default=None, help="HF Hub repo id to push to, e.g. org/my-model")
    parser.add_argument("--hf-token", default=None, help="HF API token (or set HF_TOKEN env var)")
    args = parser.parse_args()
    export(args.ckpt, args.out, push_to_hub=args.push_to_hub, hf_token=args.hf_token)


if __name__ == "__main__":
    main()
