# @package _global_

defaults:
  - _self_
  - data: image_classifier_baseline # choose datamodule with `test_dataloader()` for evaluation
  - model: acevedo_baseline
  - logger: wandb
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "predict"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: logs/train/runs/2025-09-10_11-18-57/checkpoints/last.ckpt
