# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - data: acevedo_image_classifier #mnist #acevedo # override img_augmentations in data config if needed
  - model: timm_sngp_classifier #mnist #acevedo_baseline
  - callbacks: default
  - logger: wandb # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - _self_

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

  # config for hyperparameter optimization
  - hparams_search: null

  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

# task name, determines output directory path
task_name: "train"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
tags: ["sngp_10-16", "jjn_multirun"]

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: False

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: null

# flag for torch precision: 'medium', 'high' or 'highest'
precision: "medium"

# multirun config
hydra:
  mode: MULTIRUN
  sweep:
    dir: ${paths.root_dir}/multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${model.name}_${net.trainable_kernel_scale}_${seed}
  run:
    dir: ${paths.root_dir}/runs/${model.name}_${net.trainable_kernel_scale}_seed-${seed}_${now:%H-%M-%S}

  # param sweep combinations
  sweeper:
    params:
      model: timm_sngp_classifier,timm_basic_classifier
      +net.trainable_kernel_scale: true,false # keep '+' to prevent hydra config error for models that don't have this param
      +net.scale_random_features: true,false # keep '+' to prevent hydra config error for models that don't have this param
      seed: 0,1,1234,380843,42 # https://blog.semicolonsoftware.de/the-most-popular-random-seeds/
